[2025-06-06T06:37:48.536+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LR_duration_prediction_training.train_model manual__2025-06-06T06:37:47.123469+00:00 [queued]>
[2025-06-06T06:37:48.542+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LR_duration_prediction_training.train_model manual__2025-06-06T06:37:47.123469+00:00 [queued]>
[2025-06-06T06:37:48.543+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-06-06T06:37:48.552+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): train_model> on 2025-06-06 06:37:47.123469+00:00
[2025-06-06T06:37:48.559+0000] {standard_task_runner.py:60} INFO - Started process 239 to run task
[2025-06-06T06:37:48.561+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'LR_duration_prediction_training', 'train_model', 'manual__2025-06-06T06:37:47.123469+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/LR_duration-prediction_dag.py', '--cfg-path', '/tmp/tmpvzi5b_gn']
[2025-06-06T06:37:48.563+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask train_model
[2025-06-06T06:37:48.573+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-06T06:37:48.601+0000] {task_command.py:423} INFO - Running <TaskInstance: LR_duration_prediction_training.train_model manual__2025-06-06T06:37:47.123469+00:00 [running]> on host bf22f3377e8a
[2025-06-06T06:37:48.671+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='LR_duration_prediction_training' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-06-06T06:37:47.123469+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-06T06:37:47.123469+00:00'
[2025-06-06T06:37:49.623+0000] {logging_mixin.py:188} INFO - Loaded records: 72044
[2025-06-06T06:37:49.822+0000] {logging_mixin.py:188} INFO - Records after preparation: 69392
[2025-06-06T06:37:50.479+0000] {logging_mixin.py:188} INFO - Loaded records: 65392
[2025-06-06T06:37:50.648+0000] {logging_mixin.py:188} INFO - Records after preparation: 62979
[2025-06-06T06:37:51.001+0000] {logging_mixin.py:188} WARNING - 2025/06/06 06:37:51 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-06T06:37:51.255+0000] {logging_mixin.py:188} INFO - Model intercept: 22.91
[2025-06-06T06:37:51.281+0000] {logging_mixin.py:188} INFO - MLflow Tracking URI: http://mlflow:5000
[2025-06-06T06:37:51.298+0000] {logging_mixin.py:188} INFO - MLflow Artifact URI (before logging artifact): /opt/***/mlruns/3/f175b895ed6d46f588c01681c42ea0da/artifacts
[2025-06-06T06:37:52.810+0000] {logging_mixin.py:188} WARNING - 2025/06/06 06:37:52 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-06T06:37:53.062+0000] {logging_mixin.py:188} WARNING - 2025/06/06 06:37:53 INFO mlflow.tracking._tracking_service.client: üèÉ View run smiling-grub-455 at: http://mlflow:5000/#/experiments/3/runs/f175b895ed6d46f588c01681c42ea0da.
[2025-06-06T06:37:53.063+0000] {logging_mixin.py:188} WARNING - 2025/06/06 06:37:53 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/3.
[2025-06-06T06:37:53.074+0000] {logging_mixin.py:188} INFO - Model trained and logged with run_id: f175b895ed6d46f588c01681c42ea0da
[2025-06-06T06:37:53.079+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-06-06T06:37:53.087+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=LR_duration_prediction_training, task_id=train_model, execution_date=20250606T063747, start_date=20250606T063748, end_date=20250606T063753
[2025-06-06T06:37:53.112+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-06T06:37:53.125+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
