[2025-06-06T07:45:57.507+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LR_duration_prediction_training.train_model manual__2025-06-06T07:45:56.504826+00:00 [queued]>
[2025-06-06T07:45:57.513+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LR_duration_prediction_training.train_model manual__2025-06-06T07:45:56.504826+00:00 [queued]>
[2025-06-06T07:45:57.513+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-06-06T07:45:57.521+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): train_model> on 2025-06-06 07:45:56.504826+00:00
[2025-06-06T07:45:57.526+0000] {standard_task_runner.py:60} INFO - Started process 772 to run task
[2025-06-06T07:45:57.528+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'LR_duration_prediction_training', 'train_model', 'manual__2025-06-06T07:45:56.504826+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/LR_duration-prediction_dag.py', '--cfg-path', '/tmp/tmp0e9vimep']
[2025-06-06T07:45:57.530+0000] {standard_task_runner.py:88} INFO - Job 24: Subtask train_model
[2025-06-06T07:45:57.541+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-06T07:45:57.566+0000] {task_command.py:423} INFO - Running <TaskInstance: LR_duration_prediction_training.train_model manual__2025-06-06T07:45:56.504826+00:00 [running]> on host eb1ae944af40
[2025-06-06T07:45:57.620+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='LR_duration_prediction_training' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-06-06T07:45:56.504826+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-06T07:45:56.504826+00:00'
[2025-06-06T07:46:18.681+0000] {logging_mixin.py:188} INFO - Loaded records: 3403766
[2025-06-06T07:46:24.669+0000] {logging_mixin.py:188} INFO - Records after preparation: 3316216
[2025-06-06T07:46:44.112+0000] {logging_mixin.py:188} INFO - Loaded records: 3288250
[2025-06-06T07:46:49.515+0000] {logging_mixin.py:188} INFO - Records after preparation: 3199715
[2025-06-06T07:47:06.058+0000] {logging_mixin.py:188} WARNING - 2025/06/06 07:47:06 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-06T07:47:08.345+0000] {logging_mixin.py:188} INFO - Model intercept: 23.85
[2025-06-06T07:47:08.398+0000] {logging_mixin.py:188} INFO - MLflow Tracking URI: http://mlflow:5000
[2025-06-06T07:47:08.407+0000] {logging_mixin.py:188} INFO - MLflow Artifact URI (before logging artifact): /opt/***/mlruns/3/a9d8a248dad640c298f1e3c1f3db5368/artifacts
[2025-06-06T07:47:09.872+0000] {logging_mixin.py:188} WARNING - 2025/06/06 07:47:09 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-06T07:47:09.899+0000] {logging_mixin.py:188} WARNING - 2025/06/06 07:47:09 INFO mlflow.tracking._tracking_service.client: üèÉ View run big-calf-891 at: http://mlflow:5000/#/experiments/3/runs/a9d8a248dad640c298f1e3c1f3db5368.
[2025-06-06T07:47:09.899+0000] {logging_mixin.py:188} WARNING - 2025/06/06 07:47:09 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/3.
[2025-06-06T07:47:09.910+0000] {logging_mixin.py:188} INFO - Model trained and logged with run_id: a9d8a248dad640c298f1e3c1f3db5368
[2025-06-06T07:47:10.127+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-06-06T07:47:10.135+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=LR_duration_prediction_training, task_id=train_model, execution_date=20250606T074556, start_date=20250606T074557, end_date=20250606T074710
[2025-06-06T07:47:10.206+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-06T07:47:10.218+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
