[2025-06-06T07:33:55.768+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LR_duration_prediction_training.train_model manual__2025-06-06T07:33:54.465808+00:00 [queued]>
[2025-06-06T07:33:55.772+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LR_duration_prediction_training.train_model manual__2025-06-06T07:33:54.465808+00:00 [queued]>
[2025-06-06T07:33:55.773+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-06-06T07:33:55.779+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): train_model> on 2025-06-06 07:33:54.465808+00:00
[2025-06-06T07:33:55.786+0000] {standard_task_runner.py:60} INFO - Started process 268 to run task
[2025-06-06T07:33:55.789+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'LR_duration_prediction_training', 'train_model', 'manual__2025-06-06T07:33:54.465808+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/LR_duration-prediction_dag.py', '--cfg-path', '/tmp/tmpnt8ubj74']
[2025-06-06T07:33:55.790+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask train_model
[2025-06-06T07:33:55.801+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-06T07:33:55.824+0000] {task_command.py:423} INFO - Running <TaskInstance: LR_duration_prediction_training.train_model manual__2025-06-06T07:33:54.465808+00:00 [running]> on host eb1ae944af40
[2025-06-06T07:33:55.884+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='LR_duration_prediction_training' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-06-06T07:33:54.465808+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-06T07:33:54.465808+00:00'
[2025-06-06T07:33:56.608+0000] {logging_mixin.py:188} INFO - Loaded records: 72044
[2025-06-06T07:33:56.794+0000] {logging_mixin.py:188} INFO - Records after preparation: 69392
[2025-06-06T07:33:57.449+0000] {logging_mixin.py:188} INFO - Loaded records: 65392
[2025-06-06T07:33:57.629+0000] {logging_mixin.py:188} INFO - Records after preparation: 62979
[2025-06-06T07:33:57.984+0000] {logging_mixin.py:188} WARNING - 2025/06/06 07:33:57 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-06T07:33:58.027+0000] {logging_mixin.py:188} INFO - Model intercept: 22.91
[2025-06-06T07:33:58.055+0000] {logging_mixin.py:188} INFO - MLflow Tracking URI: http://mlflow:5000
[2025-06-06T07:33:58.309+0000] {logging_mixin.py:188} INFO - MLflow Artifact URI (before logging artifact): /opt/***/mlruns/3/18623b0a61654d79931d12e8f06c3415/artifacts
[2025-06-06T07:33:59.739+0000] {logging_mixin.py:188} WARNING - 2025/06/06 07:33:59 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-06T07:33:59.765+0000] {logging_mixin.py:188} WARNING - 2025/06/06 07:33:59 INFO mlflow.tracking._tracking_service.client: üèÉ View run rebellious-perch-247 at: http://mlflow:5000/#/experiments/3/runs/18623b0a61654d79931d12e8f06c3415.
[2025-06-06T07:33:59.765+0000] {logging_mixin.py:188} WARNING - 2025/06/06 07:33:59 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/3.
[2025-06-06T07:33:59.778+0000] {logging_mixin.py:188} INFO - Model trained and logged with run_id: 18623b0a61654d79931d12e8f06c3415
[2025-06-06T07:33:59.785+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-06-06T07:33:59.794+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=LR_duration_prediction_training, task_id=train_model, execution_date=20250606T073354, start_date=20250606T073355, end_date=20250606T073359
[2025-06-06T07:33:59.818+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-06T07:33:59.830+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
