[2025-06-06T05:51:21.024+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LR_duration_prediction_training.train_model manual__2025-06-06T05:51:19.980017+00:00 [queued]>
[2025-06-06T05:51:21.032+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LR_duration_prediction_training.train_model manual__2025-06-06T05:51:19.980017+00:00 [queued]>
[2025-06-06T05:51:21.032+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-06-06T05:51:21.044+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): train_model> on 2025-06-06 05:51:19.980017+00:00
[2025-06-06T05:51:21.051+0000] {standard_task_runner.py:60} INFO - Started process 256 to run task
[2025-06-06T05:51:21.053+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'LR_duration_prediction_training', 'train_model', 'manual__2025-06-06T05:51:19.980017+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/LR_duration-prediction_dag.py', '--cfg-path', '/tmp/tmpzznih44n']
[2025-06-06T05:51:21.055+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask train_model
[2025-06-06T05:51:21.065+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-06T05:51:21.097+0000] {task_command.py:423} INFO - Running <TaskInstance: LR_duration_prediction_training.train_model manual__2025-06-06T05:51:19.980017+00:00 [running]> on host d1e68875bc3a
[2025-06-06T05:51:21.170+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='LR_duration_prediction_training' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-06-06T05:51:19.980017+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-06T05:51:19.980017+00:00'
[2025-06-06T05:51:46.216+0000] {logging_mixin.py:188} INFO - Loaded records: 3403766
[2025-06-06T05:51:52.176+0000] {logging_mixin.py:188} INFO - Records after preparation: 3316216
[2025-06-06T05:52:13.391+0000] {logging_mixin.py:188} INFO - Loaded records: 3288250
[2025-06-06T05:52:18.912+0000] {logging_mixin.py:188} INFO - Records after preparation: 3199715
[2025-06-06T05:52:35.644+0000] {logging_mixin.py:188} WARNING - 2025/06/06 05:52:35 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-06T05:52:39.578+0000] {logging_mixin.py:188} INFO - Model intercept: 23.85
[2025-06-06T05:52:39.641+0000] {logging_mixin.py:188} INFO - MLflow Tracking URI: http://mlflow:5000
[2025-06-06T05:52:39.658+0000] {logging_mixin.py:188} INFO - MLflow Artifact URI (before logging artifact): /opt/***/mlruns/2/c55a6e29b0e54ff9972273f58ad38380/artifacts
[2025-06-06T05:52:41.467+0000] {logging_mixin.py:188} WARNING - 2025/06/06 05:52:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-06T05:52:41.490+0000] {logging_mixin.py:188} WARNING - 2025/06/06 05:52:41 INFO mlflow.tracking._tracking_service.client: üèÉ View run bemused-hare-109 at: http://mlflow:5000/#/experiments/2/runs/c55a6e29b0e54ff9972273f58ad38380.
[2025-06-06T05:52:41.490+0000] {logging_mixin.py:188} WARNING - 2025/06/06 05:52:41 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/2.
[2025-06-06T05:52:41.503+0000] {logging_mixin.py:188} INFO - Model trained and logged with run_id: c55a6e29b0e54ff9972273f58ad38380
[2025-06-06T05:52:41.698+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-06-06T05:52:41.707+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=LR_duration_prediction_training, task_id=train_model, execution_date=20250606T055119, start_date=20250606T055121, end_date=20250606T055241
[2025-06-06T05:52:41.769+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-06T05:52:41.786+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
